# TCL File Generated by Component Editor 15.0
# Wed Jan 15 03:30:06 CST 2020
# DO NOT MODIFY


# 
# scorer "scorer" v1.0
#  2020.01.15.03:30:06
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module scorer
# 
set_module_property DESCRIPTION ""
set_module_property NAME scorer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME scorer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fft_n_ifft
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_fft_dual_port_ram.vhd VHDL PATH scoring/submodules/altera_fft_dual_port_ram.vhd
add_fileset_file altera_fft_dual_port_rom.vhd VHDL PATH scoring/submodules/altera_fft_dual_port_rom.vhd
add_fileset_file altera_fft_mult_add.vhd VHDL PATH scoring/submodules/altera_fft_mult_add.vhd
add_fileset_file altera_fft_single_port_rom.vhd VHDL PATH scoring/submodules/altera_fft_single_port_rom.vhd
add_fileset_file altera_reset_controller.sdc SDC PATH scoring/submodules/altera_reset_controller.sdc
add_fileset_file altera_reset_controller.v VERILOG PATH scoring/submodules/altera_reset_controller.v
add_fileset_file altera_reset_synchronizer.v VERILOG PATH scoring/submodules/altera_reset_synchronizer.v
add_fileset_file apn_fft_mult_can.vhd VHDL PATH scoring/submodules/apn_fft_mult_can.vhd
add_fileset_file apn_fft_mult_cpx.vhd VHDL PATH scoring/submodules/apn_fft_mult_cpx.vhd
add_fileset_file apn_fft_mult_cpx_1825.v VERILOG PATH scoring/submodules/apn_fft_mult_cpx_1825.v
add_fileset_file auk_dspip_avalon_streaming_block_sink.vhd VHDL PATH scoring/submodules/auk_dspip_avalon_streaming_block_sink.vhd
add_fileset_file auk_dspip_avalon_streaming_block_source.vhd VHDL PATH scoring/submodules/auk_dspip_avalon_streaming_block_source.vhd
add_fileset_file auk_dspip_bit_reverse_addr_control.vhd VHDL PATH scoring/submodules/auk_dspip_bit_reverse_addr_control.vhd
add_fileset_file auk_dspip_bit_reverse_core.vhd VHDL PATH scoring/submodules/auk_dspip_bit_reverse_core.vhd
add_fileset_file auk_dspip_bit_reverse_reverse_carry_adder.vhd VHDL PATH scoring/submodules/auk_dspip_bit_reverse_reverse_carry_adder.vhd
add_fileset_file auk_dspip_fpcompiler_alufp.vhd VHDL PATH scoring/submodules/auk_dspip_fpcompiler_alufp.vhd
add_fileset_file auk_dspip_fpcompiler_aslf.vhd VHDL PATH scoring/submodules/auk_dspip_fpcompiler_aslf.vhd
add_fileset_file auk_dspip_fpcompiler_asrf.vhd VHDL PATH scoring/submodules/auk_dspip_fpcompiler_asrf.vhd
add_fileset_file auk_dspip_fpcompiler_castftox.vhd VHDL PATH scoring/submodules/auk_dspip_fpcompiler_castftox.vhd
add_fileset_file auk_dspip_fpcompiler_castxtof.vhd VHDL PATH scoring/submodules/auk_dspip_fpcompiler_castxtof.vhd
add_fileset_file auk_dspip_fpcompiler_clzf.vhd VHDL PATH scoring/submodules/auk_dspip_fpcompiler_clzf.vhd
add_fileset_file auk_dspip_fpcompiler_mulfp.vhd VHDL PATH scoring/submodules/auk_dspip_fpcompiler_mulfp.vhd
add_fileset_file auk_dspip_lib_pkg.vhd VHDL PATH scoring/submodules/auk_dspip_lib_pkg.vhd
add_fileset_file auk_dspip_math_pkg.vhd VHDL PATH scoring/submodules/auk_dspip_math_pkg.vhd
add_fileset_file auk_dspip_r22sdf_adder_fp.vhd VHDL PATH scoring/submodules/auk_dspip_r22sdf_adder_fp.vhd
add_fileset_file auk_dspip_r22sdf_addsub.vhd VHDL PATH scoring/submodules/auk_dspip_r22sdf_addsub.vhd
add_fileset_file auk_dspip_r22sdf_bf_control.vhd VHDL PATH scoring/submodules/auk_dspip_r22sdf_bf_control.vhd
add_fileset_file auk_dspip_r22sdf_bfi.vhd VHDL PATH scoring/submodules/auk_dspip_r22sdf_bfi.vhd
add_fileset_file auk_dspip_r22sdf_bfii.vhd VHDL PATH scoring/submodules/auk_dspip_r22sdf_bfii.vhd
add_fileset_file auk_dspip_r22sdf_cma.vhd VHDL PATH scoring/submodules/auk_dspip_r22sdf_cma.vhd
add_fileset_file auk_dspip_r22sdf_cma_adder_fp.vhd VHDL PATH scoring/submodules/auk_dspip_r22sdf_cma_adder_fp.vhd
add_fileset_file auk_dspip_r22sdf_cma_bfi_fp.vhd VHDL PATH scoring/submodules/auk_dspip_r22sdf_cma_bfi_fp.vhd
add_fileset_file auk_dspip_r22sdf_core.vhd VHDL PATH scoring/submodules/auk_dspip_r22sdf_core.vhd
add_fileset_file auk_dspip_r22sdf_counter.vhd VHDL PATH scoring/submodules/auk_dspip_r22sdf_counter.vhd
add_fileset_file auk_dspip_r22sdf_delay.vhd VHDL PATH scoring/submodules/auk_dspip_r22sdf_delay.vhd
add_fileset_file auk_dspip_r22sdf_enable_control.vhd VHDL PATH scoring/submodules/auk_dspip_r22sdf_enable_control.vhd
add_fileset_file auk_dspip_r22sdf_lib_pkg.vhd VHDL PATH scoring/submodules/auk_dspip_r22sdf_lib_pkg.vhd
add_fileset_file auk_dspip_r22sdf_stage.vhd VHDL PATH scoring/submodules/auk_dspip_r22sdf_stage.vhd
add_fileset_file auk_dspip_r22sdf_stg_out_pipe.vhd VHDL PATH scoring/submodules/auk_dspip_r22sdf_stg_out_pipe.vhd
add_fileset_file auk_dspip_r22sdf_stg_pipe.vhd VHDL PATH scoring/submodules/auk_dspip_r22sdf_stg_pipe.vhd
add_fileset_file auk_dspip_r22sdf_top.ocp OTHER PATH scoring/submodules/auk_dspip_r22sdf_top.ocp
add_fileset_file auk_dspip_r22sdf_top.vhd VHDL PATH scoring/submodules/auk_dspip_r22sdf_top.vhd
add_fileset_file auk_dspip_r22sdf_twrom.vhd VHDL PATH scoring/submodules/auk_dspip_r22sdf_twrom.vhd
add_fileset_file auk_dspip_roundsat.vhd VHDL PATH scoring/submodules/auk_dspip_roundsat.vhd
add_fileset_file auk_dspip_text_pkg.vhd VHDL PATH scoring/submodules/auk_dspip_text_pkg.vhd
add_fileset_file auk_fft_pkg.vhd VHDL PATH scoring/submodules/auk_fft_pkg.vhd
add_fileset_file fft_n_ifft_fft_ii_0.sv SYSTEM_VERILOG PATH scoring/submodules/fft_n_ifft_fft_ii_0.sv
add_fileset_file fft_n_ifft_fft_ii_0.sv.bak OTHER PATH scoring/submodules/fft_n_ifft_fft_ii_0.sv.bak
add_fileset_file fft_n_ifft_fft_ii_0_opt_twi1.hex HEX PATH scoring/submodules/fft_n_ifft_fft_ii_0_opt_twi1.hex
add_fileset_file fft_n_ifft_fft_ii_0_opt_twi2.hex HEX PATH scoring/submodules/fft_n_ifft_fft_ii_0_opt_twi2.hex
add_fileset_file fft_n_ifft_fft_ii_0_opt_twi3.hex HEX PATH scoring/submodules/fft_n_ifft_fft_ii_0_opt_twi3.hex
add_fileset_file fft_n_ifft_fft_ii_0_opt_twi4.hex HEX PATH scoring/submodules/fft_n_ifft_fft_ii_0_opt_twi4.hex
add_fileset_file fft_n_ifft_fft_ii_0_opt_twi5.hex HEX PATH scoring/submodules/fft_n_ifft_fft_ii_0_opt_twi5.hex
add_fileset_file fft_n_ifft_fft_ii_0_opt_twr1.hex HEX PATH scoring/submodules/fft_n_ifft_fft_ii_0_opt_twr1.hex
add_fileset_file fft_n_ifft_fft_ii_0_opt_twr2.hex HEX PATH scoring/submodules/fft_n_ifft_fft_ii_0_opt_twr2.hex
add_fileset_file fft_n_ifft_fft_ii_0_opt_twr3.hex HEX PATH scoring/submodules/fft_n_ifft_fft_ii_0_opt_twr3.hex
add_fileset_file fft_n_ifft_fft_ii_0_opt_twr4.hex HEX PATH scoring/submodules/fft_n_ifft_fft_ii_0_opt_twr4.hex
add_fileset_file fft_n_ifft_fft_ii_0_opt_twr5.hex HEX PATH scoring/submodules/fft_n_ifft_fft_ii_0_opt_twr5.hex
add_fileset_file fft_n_ifft.sv SYSTEM_VERILOG PATH scoring/fft_n_ifft.sv TOP_LEVEL_FILE
add_fileset_file scoring.sv SYSTEM_VERILOG PATH scoring/scoring.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 50000000
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk i_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset i_reset_n reset_n Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clk
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave i_write_data writedata Input 32
add_interface_port avalon_slave o_read_data readdata Output 32
add_interface_port avalon_slave i_addr address Input 3
add_interface_port avalon_slave i_chip_sel chipselect Input 1
add_interface_port avalon_slave i_write_en write Input 1
add_interface_port avalon_slave o_scoring_finished endofpacket Output 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

